export const QUERY_REFERENCE_KEY = 'QUERY_REFERENCE_KEY';
export const QUERY_REFERENCE_CREATE = 'QUERY_REFERENCE_CREATE';
export const QUERY_REFERENCE_EDIT = 'QUERY_REFERENCE_EDIT';
export const QUERY_REFERENCE_GET = 'QUERY_REFERENCE_GET';
export const QUERY_REFERENCE_GET_ALL = 'QUERY_REFERENCE_GET_ALL';

export const QUERY_GUESTBOOK_CREATE = 'QUERY_GUESTBOOK_CREATE';

export const QUERY_ALGORITHM_CREATE = 'QUERY_ALGORITHM_CREATE';
